# Generated by Django 5.0 on 2025-05-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_position_staff_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Department',
            new_name='position',
        ),
    ]
